import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const generateReportPDF = (
  branchName: string,
  dateRange: { from: string; to: string },
  salesData: any[],
  totalRevenue: number
) => {
  const doc = new jsPDF() as any;

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('HIMCREAM - Sales Report', 14, 20);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Branch: ${branchName}`, 14, 30);
  const fromStr = dateRange.from ? format(new Date(dateRange.from), 'dd MMM yyyy') : 'Start';
  const toStr = dateRange.to ? format(new Date(dateRange.to), 'dd MMM yyyy') : 'End';
  doc.text(`Date Range: ${fromStr} to ${toStr}`, 14, 38);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Revenue: Rs. ${totalRevenue.toFixed(2)}`, 14, 48);

  const tableColumn = branchName === 'All Branches' 
    ? ["Date", "Branch", "Item", "Category", "Qty", "Price", "Total", "Profit"]
    : ["Date", "Item", "Category", "Qty", "Price", "Total", "Profit"];

  const tableRows: any[] = [];

  salesData.forEach(sale => {
    const row = [
      format(new Date(sale.createdAt), 'dd MMM yyyy, p')
    ];
    if (branchName === 'All Branches') {
      row.push(sale.branchId?.name || 'Unknown');
    }
    const product = sale.productId || sale.globalProductId || {};
    row.push(
      product.name || 'Unknown',
      product.category || '-',
      sale.quantity.toString(),
      `Rs. ${(sale.priceAtSale || sale.price || sale.transferRate || product.price || 0).toFixed(2)}`,
      `Rs. ${sale.totalAmount.toFixed(2)}`,
      sale.totalProfit !== undefined ? `Rs. ${sale.totalProfit.toFixed(2)}` : '-'
    );
    tableRows.push(row);
  });

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 55,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] }, // blue-600
  });

  doc.save(`${branchName.replace(/\s+/g, '_')}_Sales_Report_${Date.now()}.pdf`);
};

export const generateTransferReceiptPDF = (
  branchName: string,
  managerName: string,
  items: any[],
  total: number,
  download: boolean = true
) => {
  const height = Math.max(200, 75 + (items.length * 8));
  const doc = new jsPDF({
    unit: 'mm',
    format: [80, height]
  });

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('STOCK TRANSFER BILL', 40, 12, { align: 'center' });
  
  doc.setFontSize(10);
  doc.text(`To: ${branchName}`, 40, 18, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Manager: ${managerName}`, 40, 23, { align: 'center' });
  doc.text(`Date: ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`, 40, 28, { align: 'center' });
  
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(5, 32, 75, 32);

  let y = 37;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('ITEM', 5, y);
  doc.text('QTY', 48, y, { align: 'center' });
  doc.text('VALUE', 75, y, { align: 'right' });
  
  y += 3;
  doc.setLineWidth(0.2);
  doc.line(5, y, 75, y);
  y += 5;

  doc.setFont('helvetica', 'normal');
  items.forEach(item => {
    const name = `${item.name} (${item.unit})`.slice(0, 24);
    doc.text(name, 5, y);
    doc.text(item.quantity.toString(), 48, y, { align: 'center' });
    const amount = (item.price * item.quantity).toFixed(2);
    doc.text(amount, 75, y, { align: 'right' });
    y += 6;
  });

  doc.setLineWidth(0.5);
  doc.line(5, y, 75, y);
  y += 6;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTAL VALUE:', 5, y);
  doc.text(`Rs. ${total.toFixed(2)}`, 75, y, { align: 'right' });
  
  y += 12;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by HIMCREAM', 40, y, { align: 'center' });
  doc.setTextColor(150, 150, 150);
  doc.text('Software Generated Receipt', 40, y + 4, { align: 'center' });

  if (download) {
    doc.save(`Transfer_Bill_${branchName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
  }
  return doc.output('datauristring');
};

export const generateReceiptPDF = (
  branchName: string,
  items: any[],
  total: number,
  download: boolean = true
) => {
  // dynamic height calculation based on items
  const height = Math.max(200, 60 + (items.length * 8));
  const doc = new jsPDF({
    unit: 'mm',
    format: [80, height] // 80mm thermal paper width
  });

  // Header Layout
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('HIMCREAM', 40, 12, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(branchName, 40, 18, { align: 'center' });
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Receipt Date: ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`, 40, 23, { align: 'center' });
  
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(5, 27, 75, 27);

  // Table Headers
  let y = 32;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('ITEM DESC', 5, y);
  doc.text('QTY', 48, y, { align: 'center' });
  doc.text('AMOUNT', 75, y, { align: 'right' });
  
  y += 3;
  doc.setLineWidth(0.2);
  doc.line(5, y, 75, y);
  y += 5;

  // Items List
  doc.setFont('helvetica', 'normal');
  items.forEach(item => {
    // Break product name if too long
    const name = `${item.name} (${item.unit})`.slice(0, 24);
    doc.text(name, 5, y);
    doc.text(item.quantity.toString(), 48, y, { align: 'center' });
    const amount = (item.price * item.quantity).toFixed(2);
    doc.text(amount, 75, y, { align: 'right' });
    if(item.note) {
      y += 4;
      doc.setFontSize(7);
      doc.setTextColor(100, 100, 100);
      doc.text(`* ${item.note.slice(0,30)}`, 7, y);
      doc.setFontSize(8);
      doc.setTextColor(0, 0, 0);
    }
    y += 6;
  });

  doc.setLineWidth(0.5);
  doc.line(5, y, 75, y);
  y += 6;

  // Totals
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTAL:', 5, y);
  doc.text(`Rs. ${total.toFixed(2)}`, 75, y, { align: 'right' });
  
  y += 12;
  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Thank you for choosing HIMCREAM!', 40, y, { align: 'center' });
  doc.setTextColor(150, 150, 150);
  doc.text('Visit again', 40, y + 4, { align: 'center' });

  // Output
  if (download) {
    doc.save(`receipt_${Date.now()}.pdf`);
  }
  return doc.output('datauristring');
};
